
CREATE ROLE academy LOGIN
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

ALTER USER academy WITH PASSWORD 'academy';

ALTER USER academy WITH SUPERUSER;

CREATE DATABASE academy_db
  WITH OWNER = postgres
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'en_US.utf8'
       LC_CTYPE = 'en_US.utf8'
       CONNECTION LIMIT = -1;
GRANT CONNECT, TEMPORARY ON DATABASE fms_db TO public;

GRANT ALL ON DATABASE academy_db TO postgres;
GRANT ALL ON DATABASE academy_db TO academy;